In [2]:
import pandas as pd 
import numpy as np

In [3]:
pd.__version__

'2.3.2'

In [47]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [48]:
df.head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Q2. Records count

In [49]:
len(df)

9704

### Q3. Fuel types

In [50]:
df.fuel_type.nunique()

2

### Q4. Missing values

In [51]:
df.isnull().sum()[df.isnull().sum() > 0]

num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

### Q5. Max fuel efficiency

In [52]:
round(df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max(), 3)

23.759

### Q6. Median value of horsepower

In [53]:
median_horsepower = df['horsepower'].median()
median_horsepower

149.0

In [54]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [55]:
# confirmattion of the most frequent
df['horsepower'].value_counts().iloc[0:5]

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
Name: count, dtype: int64

In [56]:
mode_horsepower = df['horsepower'].mode()
mode_horsepower

0    152.0
Name: horsepower, dtype: float64

In [59]:
df['horsepower'] = df['horsepower'].fillna(mode_horsepower)

In [60]:
new_median_horsepower = df['horsepower'].median()
new_median_horsepower

149.0

### Q7. Sum of weights

In [70]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].iloc[0:7].values

In [71]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [72]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [85]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.50732678],
       [41431216.50732678, 28373339.        ]])

In [86]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [87]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [90]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [93]:
round(w.sum(), 3)

np.float64(0.519)